POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Reiner", 
  "number": 8889
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Gojo", 
  "number": 33300 
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
  "name": "",
  "number": 0
}