POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Captain",
  "name": "Monkey D. Luffy",
  "password": "cap'n"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "First Mate",
  "name": "Roronoa Zoro",
  "password": "sweet"
}