POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "first",
  "name": "luffy"
}
###
# username too short
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "sec",
  "name": "zolo",
  "password": "sw"
}