DELETE http://localhost:3003/api/blogs/60ec7f91cf05c0335031abcd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNhcHRhaW4iLCJpZCI6IjYwZWM3ZjZlY2YwNWMwMzM1MDMxYWJiZSIsImlhdCI6MTYyNjM1ODc2N30.6ZkHSL7ELYXJnTCPV6oCdJc9Xpwj9I1tFVAB5pboE4c